spring.application.name=veebipood
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d6s30pvafjfc73eo90tg-a.frankfurt-postgres.render.com/veebipood_1d93
spring.datasource.username=veebipood_user
spring.datasource.password=QO4sGbDhaP7vfzLbTjq1927gAlOsa1M3